config/routes.rb
Engine49688::Engine.routes.draw do
  resources :articles
end

app/models/engine49688/application_record.rb
module Engine49688
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/engine49688/article.rb
module Engine49688
  class Article < ApplicationRecord
  end
end

app/controllers/engine49688/application_controller.rb
module Engine49688
  class ApplicationController < ActionController::Base
  end
end

app/controllers/engine49688/articles_controller.rb
module Engine49688
  class ArticlesController < ApplicationController
    before_action :set_article, only: %i[ show edit update destroy ]

    # GET /articles
    def index
      @articles = Article.all
    end

    # GET /articles/1
    def show
    end

    # GET /articles/new
    def new
      @article = Article.new
    end

    # GET /articles/1/edit
    def edit
    end

    # POST /articles
    def create
      @article = Article.new(article_params)

      if @article.save
        redirect_to @article, notice: "Article was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /articles/1
    def update
      if @article.update(article_params)
        redirect_to @article, notice: "Article was successfully updated.", status: :see_other
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /articles/1
    def destroy
      @article.destroy!
      redirect_to articles_url, notice: "Article was successfully destroyed.", status: :see_other
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_article
        @article = Article.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def article_params
        params.require(:article).permit(:title, :text)
      end
  end
end

app/helpers/engine49688/application_helper.rb
module Engine49688
  module ApplicationHelper
  end
end

app/helpers/engine49688/articles_helper.rb
module Engine49688
  module ArticlesHelper
  end
end

app/views/engine49688/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= article.text %>
  </p>

</div>

app/views/engine49688/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_area :text %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/engine49688/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/engine49688/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Articles</h1>

<div id="articles">
  <% @articles.each do |article| %>
    <%= render article %>
    <p>
      <%= link_to "Show this article", article %>
    </p>
  <% end %>
</div>

<%= link_to "New article", new_article_path %>

app/views/engine49688/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/engine49688/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/layouts/engine49688/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Engine49688</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    "engine49688/application", media: "all" %>
</head>
<body>

<%= yield %>

</body>
</html>